@IsTest
private class DivvyTest {
  @IsTest
  static void registerReadSingleRecordIdSingleUserOrGroupId() {
    Divvy.newInstance();
  }

  @IsTest
  static void registerEditSingleRecordIdSingleUserOrGroupId() {
    System.assert(false);
  }

  @IsTest
  static void registerRevokeSingleRecordIdSingleUserOrGroupId() {
    System.assert(false);
  }

  @IsTest
  static void registerReadSingleRecordSingleUserOrGroupId() {
    System.assert(false);
  }

  @IsTest
  static void registerEditSingleRecordSingleUserOrGroupId() {
    System.assert(false);
  }

  @IsTest
  static void registerRevokeSingleRecordSingleUserOrGroupId() {
    System.assert(false);
  }

  @IsTest
  static void registerReadMultipleRecordsSingleUserOrGroupId() {
    System.assert(false);
  }

  @IsTest
  static void registerEditMultipleRecordsSingleUserOrGroupId() {
    System.assert(false);
  }

  @IsTest
  static void registerRevokeMultipleRecordsSingleUserOrGroupId() {
    System.assert(false);
  }

  @IsTest
  static void registerReadSingleRecordMultipleUserOrGroupIds() {
    System.assert(false);
  }

  @IsTest
  static void registerEditSingleRecordMultipleUserOrGroupIds() {
    System.assert(false);
  }

  @IsTest
  static void registerRevokeSingleRecordMultipleUserOrGroupIds() {
    System.assert(false);
  }

  @IsTest
  static void registerReadSingleRecordIdMultipleUserOrGroupIds() {
    System.assert(false);
  }

  @IsTest
  static void registerEditSingleRecordIdMultipleUserOrGroupIds() {
    System.assert(false);
  }

  @IsTest
  static void registerRevokeSingleRecordIdMultipleUserOrGroupIds() {
    System.assert(false);
  }

  @IsTest
  static void registerReadMultipleRecordsMultipleUserOrGroupIds() {
    System.assert(false);
  }

  @IsTest
  static void registerEditMultipleRecordsMultipleUserOrGroupIds() {
    System.assert(false);
  }

  @IsTest
  static void registerRevokeMultipleRecordsMultipleUserOrGroupIds() {
    System.assert(false);
  }
}
