name: Run Apex Tests

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          repository: ${{github.head.repo.full_name}}

      - name: Install Salesforce CLI and authorize DevHub
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.DEVHUB_URL }}
      - run: sfdx force:org:create -f config/project-scratch-def.json --setdefaultusername -d 1
      - run: sfdx force:source:push
      - run: sfdx force:apex:test:run -w 5
      - run: sfdx force:org:delete -p
        if: always()